# Generated by Django 4.2 on 2023-04-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
