# Generated by Django 4.2 on 2023-04-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_likeanswers_likequestions_delete_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeAnswers',
            new_name='LikeAnswer',
        ),
        migrations.RenameModel(
            old_name='LikeQuestions',
            new_name='LikeQuestion',
        ),
    ]
