# Generated by Django 4.2 on 2023-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeanswer',
            name='estimation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='likequestion',
            name='estimation',
            field=models.BooleanField(default=True),
        ),
    ]
